app.config(function($routeProvider){
   $routeProvider.
           when('/coordReserve',{
               templateUrl:'./templates/principalReserves.html',
               controller:'pReserveController'
           }).when('/editSchedule',{
               templateUrl:'./templates/editScheduleCoordination.html',
               controller:'editScheduleController'
           }).when('/createUpdateReserve',{
               templateUrl:'./templates/createUpdateReserve.html',
               controller:'createUpdateController'
           }).when('/searchMakeReserve',{
               templateUrl:'./templates/searchMakeReserve.html',
               controller:'searchMakeController'
           }).when('/blackList',{
               templateUrl:'./templates/blackList.html',
               controller:'blackListController'
           }).when('/cancelReserves',{
               templateUrl:'./templates/cancelReserve.html',
               controller:'cancelReserveController'
           }).when('/addBlackList',{
               templateUrl:'./templates/addBlackList.html',
               controller:'blackListController'
           }).otherwise({
              redirectTo:'/coordReserve' 
           });
});